eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost
spring:
  kafka:
    bootstrap-servers: 192.168.1.7:9092
